### ISSUE TITLE
Uncaught TYPO3 Exception "" is not a valid cache entry identifier.

### ISSUE THREAD

**Issue by r4fx** [hendrikreimers/TYPO3-content_designer#8]
After update "content_designer" to 3.0.6 i got an error when i want to edit page properties

`Uncaught TYPO3 Exception
#1233058294: "" is not a valid cache entry identifier.`

my code for page settings:

```
pages.tx_contentdesigner_flexform.settings {

    tca = --div--;Settings,tx_contentdesigner_flexform

    cObject.sDEF {
        sheetTitle = Settings

        el {
            hidePageHeader {
                label = Hide page header
                config.type = check
            }

            hideAsideNav {
                label = Hide aside nav
                config.type = check
            }
        }
    }
}
```

**Comment by hendrikreimers** [comment]
At the moment, i cannot reconstruct the issue. Can you please enable the debug messages in your TYPO3?
You can do it with the following TS Setup: config.contentObjectExceptionHandler = 0 ...maybe you also need to set your installation to the dev mode in the install tool

**Comment by r4fx** [comment]
I see this

![screenshot-1](https://cloud.githubusercontent.com/assets/4216415/19237998/c5576462-8eff-11e6-9d95-b7c62b96c852.png)

**Comment by jfschubert** [comment]
Having the Same Issue, i couldn neither copy a Page nor check Reference Index

because  `$row['CType']` is not set so is added the following to the function `getFlexFormDS_postProcessDS` in `Classes/Hooks/Forms/FlexFormDs.php`

`if(!isset($row['CType'])) {
            return;
        }`

I would really check if the  the postProgressHook is needed for the given Object.

**Comment by mfell** [comment]
Hi Hendrik, I have the same problem: TYPO3 7.6.16, content_designer 3.0.7

I have a testing system, where this bug occours ... you can get a login, if needed?

Greetz from Marc :o)

**Comment by hendrikreimers** [comment]
Hi Marc,

i've stopped development at the moment. Because it becomes to complicated for newer TYPO3 versions and the mask ext. is an great alternative with a great team behind. I want to concentrate on new projects and extension ideas.

In my case i've made a kind of "provider" ext. that helps me to create real content elements as simple as possible.

If you have a solution for that bug, please make a pull request or post the code here.

Thanks a lot!

**Comment by j-lang** [comment]
Is there any solution, have same issue after update to Typo3 7.6 and update to content_designer 3.0.7
Thx

**Comment by Lobster1956** [comment]
same problem here...
my **VERY dirty** workaround in the file  _/content_designer/Classes/Hooks/Form/FlexFormDs.php_  is:
```
    $cacheIdentifier = $row['CType'];
// Modifikation Fehlervermeidung start ... RRS
        if (!$cacheIdentifier) {
            $cacheIdentifier = 'XXX';
        }
// Modifikation Fehlervermeidung end ... RRS        
    // Restore dataStructArray from cache if necessary
    $cachedDataStructArray = $cache->get($cacheIdentifier);
```
so if there is no cacheIdentifier, i set it to XXX (and so nor error occurs)
